apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: registry
spec:
  template:
    metadata:
      labels:
        app: registryapp
    spec:
      containers:
      - name: registry
        image: registry:2
        ports:
        - containerPort: 5000
          protocol: TCP
        volumeMounts:
        - name: azure
          mountPath: /mnt/azu
      volumes:
      - name: azure
        azureFile:
          secretName: azfileshare
          shareName: registry
          readOnly: false